name: Build and deploy ASP.Net Core app to Azure Web App - KEYUR-WEB-APP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build API
        run: dotnet build MedicalConsultation.API/MedicalConsultation.API.csproj --configuration Release
        working-directory: Backend/

      - name: Publish API
        run: dotnet publish MedicalConsultation.API/MedicalConsultation.API.csproj --configuration Release --output ../api_publish
        working-directory: Backend/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api_publish
          path: api_publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: api_publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_71DFCB51110E4E73BC565D19201D138A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F47D72FF30CD427ABAD70C85DC8AFF2C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EA606AB0578429E9E51168A22F4BCFA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'KEYUR-WEB-APP'
          slot-name: 'Production'
          package: .